<div id="table-content">
	<table cellspacing="0">
		<thead>
			<tr><th>ID</th><th>Name</th><th>Description</th><th>Status</th><th>URL</th><th>Path</th></tr>
		</thead>
<tbody>
	<?php
		if ($this->controllers){
			foreach ($this->controllers as $controller) {
	?>
				<tr onclick="location.href='/<?php echo $this->editor_uri; ?>/edit/<?php echo $controller['id']; ?>'">
					<td>
						<?php echo $controller['id']; ?>
					</td>
					<td>
						<?php echo $controller['name']; ?>
					</td>
					<td>
						<?php echo $controller['description']; ?>
					</td>
					<td>
						<?php if($controller['enabled']) {
							echo "enabled";
						} else {
							echo "disabled";
						}; ?>
					</td>
					<td>
						<?php echo $controller['uri_name']; ?>
					</td>
					<td>
						<?php echo $controller['file_path']; ?>
					</td>
				</tr>
	<?php
			} 
		}
	?>

		</tbody>	
	</table>
</div>
<div class="regix-form-container">
	<div class="button-holder">
	<form action="/<?php echo $this->editor_uri; ?>/add" method="post" class="regix-form">
		<div><button type="submit" class="secondary-button-single" > Add controller</button></div>		
	</form>
	</div>
</div>
