<div class="regix-form-container">
	<form action="" class="regix-form">
	<h1>Controllers</h1>
<div class="table-content">
	<table class="hover-row">
		<thead>
			<tr><th>ID</th><th>Name</th><th>Description</th><th>Status</th><th>URL</th><th>Path</th></tr>
		</thead>
<tbody>
	<?php
		if ($this->controllers){
			foreach ($this->controllers as $controller) {
	?>
				<tr onclick="location.href='/<?php echo $this->editor_uri; ?>/edit/<?php echo $controller['id']; ?>'">
					<td>
						<div>
						<?php echo $controller['id']; ?>
						</div>
					</td>
					<td>
						<div>
						<?php echo $controller['name']; ?>
						</div>
					</td>
					<td>
						<div>
						<?php echo $controller['description']; ?>
						</div>
					</td>
					<td>
						<div>
						<?php if($controller['enabled']) {
							echo "enabled";
						} else {
							echo "disabled";
						}; ?>
						</div>
					</td>
					<td>
						<div>
						<?php echo $controller['uri_name']; ?>
						</div>
					</td>
					<td>
						</div>
						<?php echo $controller['file_path']; ?>
						</div>
					</td>
				</tr>
	<?php
			} 
		}
	?>

		</tbody>	
	</table>
</div>
			</form>
	<div class="button-holder">
	<form action="/<?php echo $this->editor_uri; ?>/add" method="post" class="regix-form">
		<div><button name="submit" type="submit" class="secondary-button-single first"> Add controller</button></div>		
	</form>
	</div>
</div>
