<div class="regix-form-container">	
	<form action="/<?php echo $this->editor_uri; ?>/save/<?php echo $this->controller_data['id']; ?>" method="post" class="regix-form">
		<h1><?php echo $this->controller_data['name']; ?></h1>
		
		<div>
			<div class="form-label-container"><label>ID</label></div>
			<div class="form-label-container-bold"><label><?php echo $this->controller_data['id']; ?></label></div>
		</div>
		
		<div>
			<div class="form-label-container"><label for="name">Name</label></div>
			<input id="name" type="text" name="name" class="regix-form-input" value="<?php echo $this->controller_data['name']; ?>" />
		</div>
		
		<div>
			<div class="form-label-container"><label for="description">Description</label></div>
			<input id="description" type="text" name="description" class="regix-form-input" value="<?php echo $this->controller_data['description']; ?>" />
		</div>
		
		<div>
			<div class="form-label-container"><label for="enabled">Enabled</label></div>
			<input id="enabled" name="enabled" type="checkbox"<?php if ($this->controller_data['enabled']) { echo(' checked="checked"'); } ; ?>/>
		</div>
		
		<div>
			<div class="form-label-container"><label for="uri_name">URL</label></div>
			<input id="uri_name" type="text" name="uri_name" class="regix-form-input" value="<?php echo $this->controller_data['uri_name']; ?>" />
		</div>
		
		<div>
			<div class="form-label-container"><label for="file_path">Path</label></div>
			<input id="file_path" type="text" name="file_path" class="regix-form-input" value="<?php echo $this->controller_data['file_path']; ?>" />
		</div>

		<div class="button-holder">
			<button name="submit" type="submit" class="secondary-button">Save</button>
			<button name="cancel" type="submit" class="default-button">Cancel</button>
		</div>		
	</form>
	
	<form action="/<?php echo $this->editor_uri; ?>/delete/<?php echo $this->controller_data['id']; ?>" method="post">
		<div><button type="submit" class="warning-button-single" >Delete controller</button></div></form></div>