<div id="controller_manager_editor_container" class="table_container">
	<div class="title_block"><?php echo $this->controller_data['name']; ?></div>
	<form action="/<?php echo $this->editor_uri; ?>/save/<?php echo $this->controller_data['id']; ?>" method="post">
		<table>
			<tbody>
				<tr>
					<th>ID</th>
					<td><?php echo $this->controller_data['id']; ?></td>
				</tr>
				<tr>
					<th>Name</th>
					<td><input name="name" type="text" value="<?php echo $this->controller_data['name']; ?>" /></td>
				</tr>
				<tr>
					<th>Description</th>
					<td><input name="description" type="text" value="<?php echo $this->controller_data['description']; ?>" /></td>
				</tr>
				<tr>
					<th>Enabled</th>
					<td><input name="enabled" type="checkbox"<?php if ($this->controller_data['enabled']) { echo(' checked="checked"'); } ; ?>/>
					</td>
				</tr>
				<tr>
					<th>URL</th>
					<td><input name="uri_name" type="text" value="<?php echo $this->controller_data['uri_name']; ?>" /></td>
				</tr>
				<tr>
					<th>Path</th>
					<td><input name="file_path" type="text" value="<?php echo $this->controller_data['file_path']; ?>" /></td>
				</tr>
				<tr>
					<td colspan="2">
						<input name="submit" type="submit" value="Save" />
						<input name="cancel" type="submit" value="Cancel" />
					</td>
				</tr>
			</tbody>
		</table>
	</form>
</div>