<div class="regix-form-container">
	<form action="/<?php echo $this->editor_uri; ?>/save_new" method="post" class="regix-form">
		<h1>New Controller</h1>
		
		<div>
			<div class="form-label-container"><label for="name">Name</label></div>
			<input id="name" type="text" name="name" class="regix-form-input"/>
		</div>
		
		<div>
			<div class="form-label-container"><label for="description">Description</label></div>
			<input id="description" type="text" name="description" class="regix-form-input"/>
		</div>
		
		<div>
			<div class="form-label-container"><label for="name">Enabled</label></div>
			<input name="enabled" type="checkbox" />
		</div>
		
		<div>
			<div class="form-label-container"><label for="uri_name">URL</label></div>
			<input id="uri_name" type="text" name="uri_name" class="regix-form-input"/>
		</div>
		
		<div>
			<div class="form-label-container"><label for="file_path">Path</label></div>
			<input id="file_path" type="text" name="file_path" class="regix-form-input"/>
		</div>
		
		<div class="button-holder">
			<button name="submit" type="submit" class="secondary-button">Add</button>
			<button name="cancel" type="submit" class="default-button last">Cancel</button>
		</div>	
	</form>
</div>