<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" manifest="/cache/cache.manifest">

<head>
	<title><?php echo $this->title; ?></title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<link rel="stylesheet" href="/css/style.css" />
</head>

<body class="body_normal">
	<div id="container">
		
		<div id="header"><div id="header_user">Signed in as <a href="/prof"><?php echo $this->user_name; ?></a> <a href="/login/logout" class="no_deco">&times;</a></div></div>
		
		<div id="content">
			<?php echo $this->content; ?>
			<div class="push"></div>
		</div>
		
		<div id="footer">
			<div id="footer_content">
				<a href="/">&lt;&lt; Back to the main page</a>
			</div>
		</div>
		
	</div>

	<script src="/js/libs/jquery-2.1.0.min.js" type="text/javascript"></script>
	<script src="/js/core/Core.js" type="text/javascript"></script>
</body>
</html>
