<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title><?php echo $this->title; ?></title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<link rel="stylesheet" href="/css/style.css" />
</head>

<body class="body_normal">
	
	<div id="container">
		<div class="header warning_dark">Administrator control panel</div>
		
		<?php echo $this->content; ?>
		
		<div class="footer"><a href="/">&lt;&lt; Back to the main page</a></div>
		
	</div>

</body>
</html>
