<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Regix</title>
		<link href='http://fonts.googleapis.com/css?family=Roboto:100' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="/css/style.css" >
	</head>
	<body>
		<div class="container">
			<a href="https://courses.cs.ut.ee/2014/vl/spring" class="bl_center">
				<span>Coming soon</span>
			</a>
		</div>
        
	</body>
</html>
