<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Regix</title>
		<link href='http://fonts.googleapis.com/css?family=Roboto:100' rel='stylesheet' type='text/css'>
		<link rel="stylesheet" type="text/css" href="/css/style.css" >
	</head>
	<body>
		<div class="container">
			<div id="user_bar"><?php echo $this->user_name; ?></div>
			<a href="/login" class="bl_center">
				<span>Sign in</span>
			</a>
			<a href="/reg" class="bl_center">
				<span>Register new user</span>
			</a>
		</div>
        
	</body>
</html>
