<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title><?php echo $this->title; ?></title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<meta name="viewport" content="width=480"/>
	<link rel="stylesheet" href="/css/style.css" />
</head>

<body class="body_normal">
	<div id="container">		
		<div class="regixnav">
		<ul>
			<?php 
			if($this->user_name!="Guest"){
			echo "<li><a href=\"/login/logout\" class=\"exit\"><span>Log out</span></a>
			</li>";
			}
			?>
			<li><a href="/prof" class="navnorm"><span>Signed in as <span class="user_name"><?php echo $this->user_name; ?></span></span></a>
			</li>
			<li><a href="/" class="navnarrow"><span>MAIN PAGE</span></a>
			</li>	
		</ul>
		</div>
			
		<div id="content">
			<?php echo $this->content; ?>
			<div class="push"></div>
		</div>		
	</div>

	<script src="/js/libs/jquery-2.1.0.min.js" type="text/javascript"></script>
	<script src="/js/core/Core.js" type="text/javascript"></script>
</body>
</html>
