<a href="/login" class="bl_center">
	<span>Sign in</span>
</a>
<a href="/reg" class="bl_center">
	<span>Register new user</span>
</a>
<a href="/calendar" class="bl_center">
	<span>Book service</span>
</a>
<a href="/events" class="bl_center">
	<span>Event Manager</span>
</a>
<a href="/prof" class="bl_center">
	<span>User Profile</span>
</a>
<a href="/uac" class="bl_center">
	<span>User Manager</span>
</a>
<a href="/controllers" class="bl_center">
	<span>Controller Manager</span>
</a>
<a href="/groups" class="bl_center">
	<span>Group Manager</span>
</a>
<a href="/permissions" class="bl_center">
	<span>Permission Manager</span>
</a>