<div id="popup_top_tpl" class="popup">
	<div class="event">
		<div>New event:</div>
		<div class="time"></div>
		<div class="description"></div>
	</div>
</div>

<div class="regix-form-container">
	<form action="" class="regix-form">
	<div class="table-content">
		<table>
			<thead><tr><th colspan="7"><h1>
				<?php echo "<a class=\"no_deco\" href='/".$this->cal_uri."/".$this->service."/".$this->prevmonth."'>&lt;&lt;</a>";
				      echo date("F", mktime(0,0,0,$this->month,$this->day,$this->year));
				      echo $this->year;
				      echo "<a class=\"no_deco\" href='/".$this->cal_uri."/".$this->service."/".$this->nextmonth."'>&gt;&gt;</a>";
				?>
				</h1></th></tr></thead>
			<tr><td><div class="week-day">Monday</div></td><td><div class="week-day">Tuesday</div></td><td><div class="week-day">Wednesday</div></td><td><div class="week-day">Thursday</div></td><td><div class="week-day">Friday</div></td><td><div>Saturday</div></td><td class="last"><div class="week-day">Sunday</div></td></tr>
			<?php
			$month_stamp=mktime(0,0,0,$this->month,$this->day,$this->year);
			$day_count=date("t",$month_stamp);
			$i=$this->wd;
			echo "<tr>\n";
			if($this->wd!=1){
					for($cell=1;$cell<$this->wd;$cell++){
						echo "<td></td>";
					}
				}
			 for($d=1;$d<=$day_count;$d++) { 
				//echo $i;
				if ($i-1 == 7){
					echo " <tr>\n";
					$i=1;
				}
//				if ($i-1 == 6){
//					/* sunday element */
//					echo "<td>";
//				}
//				else{
//					echo "<td>";
//				}
				 
				$date2display = mktime(0,0,0,$this->month,$d,$this->year);
				$today = mktime(0,0,0,$this->currmonth,$this->day,$this->curryear);

				if ($date2display >= $today){
					echo " <td class=\"hover-cell\">";
					echo "<a class=\"no_deco\" href='/".$this->cal_uri."/".$this->service."/".$this->year."/".$this->month."/".$d."'>".$d."</a>";
				}
				else{
					echo " <td class=\"past-day\"><div class=\"week-day\">";
					echo $d;
					echo "</div";
				}
				echo "</td>\n";
				$i++;
				if (!($i % 8))  echo " </tr>\n";
			  } 
			?>
			</tr>
		</table>
		</div>
		</form>
</div>

<script src="/js/components/Calendar.js" type="text/javascript"></script>
