<div class="regix-form-container">
	<form action="" class="regix-form">
	<div class="table-content">
		<table class="hover-cell">
			<thead><tr><th colspan="7"><h1>
				<a href=''>&lt;&lt; </a><?php echo date("F"); ?> <?php echo $this->year; ?><a href=''> &gt;&gt; </a>
				</h1></th></tr></thead>
			<tr><td>Monday</td><td>Tuesday</td><td>Wednesday</td><td>Thursday</td><td>Friday</td><td>Saturday</td><td class="last">Sunday</td></tr>
			<?php
			$month_stamp=mktime(0,0,0,$this->month,$this->day,$this->year);
			$day_count=date("t",$month_stamp);
			$i=$this->wd;
			
			echo "<tr>\n";
			if($this->wd!=1){
					for($cell=1;$cell<$this->wd;$cell++){
							echo "<td></td>";
				}
			}
			 for($d=1;$d<=$day_count;$d++) { 
				//echo $i;
				if ($i-1 == 7){
					echo " <tr>\n";
					$i=1;
				}
				if ($i-1 == 6){
					echo "<td class=\"last\">";
				}
				else{
				echo "<td>";
				}
				echo "<a href='/".$this->cal_uri."/".$this->service."/".$this->month."/".$d."'>".$d."</a>";
				echo "</td>\n";
				$i++;
				if (!($i % 8)){  echo " </tr>\n";
			  }
			 }
			?>
			</tr>
		</table>
		</div>
		</form>
</div>
