<div id="event_registration_container" class="table_container">
	<div class="title_block">Selected Date</div>
	<div class="title_block">Day of the week</div>
	<form action="" method="post">
		<table id="event_registration_table">
			<tbody>
				<tr>
					<th class="table_row_header">Time</th>
					<td><input name="time" type="text" /></td>
				</tr>
				<tr>
					<th class="table_row_header">Worker</th>
					<td><input name="worker" type="text" /></td>
				</tr>
				<tr>
					<th class="table_row_header">Your Name</th>
					<td><input name="client_name" type="text" /></td>
				</tr>
				<tr>
					<th class="table_row_header">Comment</th>
					<td><input name="comment" type="text" /></td>
				</tr>
				<tr>
					<td colspan="2"><input name="reg_event" type="submit" value="Register" /></td>
					<td colspan="2"><input name="cancel" type="submit" value="Cancel" /></td>
				</tr>
			</tbody>
		</table>
	</form>
</div>

</div>