<div id="event_registration_container" class="table_container">
  <div class="title_block"><?php echo date("F", mktime(0,0,0,$this->month,$this->day,$this->year)); echo " ".$this->day ?></div>
  <div class="title_block"><?php echo date("l", mktime(0,0,0,$this->month,$this->day,$this->year)); ?></div>
  <form action="" method="post">
    <table id="event_registration_table">
      <tbody>
    <tr>
     <th class="table_row_header">Worker</th>
     <td class="table_row_dropdown_menu">
      <select name='worker'>
       <?php
       foreach ($this->workers_to_assign as $worker) {
      echo "<option>".$worker['name']."</option>";
       }
       ?>
      </select>
     </td>
    </tr>
    <tr>
     <th class="table_row_header">Comment</th>
     <td><input name="comment" type="text" /></td>
    </tr>
    <tr>
     <td colspan="1"><a href="/<?php echo $this->cal_uri; ?>"><input name="cancel" type="button" value="Cancel" /><a></td>
     <td colspan="1"><input name="reg_event" type="submit" value="Register" /></td>
    </tr>
   </tbody>
  </table>
 </form>
</div>

<script src="/js/components/Calendar.js"></script>