<div class="regix-form-container">
	<form action="" method="post" class="regix-form">
		<div class="table-content">
			<h1><?php echo date("F", mktime(0,0,0,$this->month,$this->day,$this->year)); echo " ".$this->day; ?></h1>
			<table>
				<thead>
			<tr><th><?php echo date("l", mktime(0,0,0,$this->month,$this->day,$this->year)); ?></th></tr></thead>
			<tbody>
			<?php
			$from=8; //working day starts (calculated using constraints)
			$to=18; //working day ends (calculated using constraints)
			for($hour=$from;$hour<$to;$hour++){
				foreach ($this->booked_hours as $booked) {
					if($booked==$hour) $hour++;
					}
				echo "<tr><td class=\"last\"><a href='/".$this->cal_uri."/".$this->service."/".$this->year."/".$this->month."/".$this->day."/".$hour."'>".$hour.":00 - ";
				$hour++;
				echo $hour.":00</a></td></tr>";
				$hour--;
			}
			?>
			</tbody>
		</table>
	</form>
</div>

<script src="/js/components/Calendar.js"></script>