<div id="popup_top_tpl" class="popup">
	<div class="event">
		<div>New event:</div>
		<div class="time"></div>
		<div class="description"></div>
	</div>
</div>

<div class="regix-form-container">
	<form action="" method="post" class="regix-form">
		<div class="table-content">
			<h1><?php 
                    $selectedDate = mktime(0,0,0,$this->month,$this->day,$this->year);
					$today = mktime(0,0,0,$this->currmonth,$this->currday,$this->curryear);
					if($today<$selectedDate){
						echo "<a class=\"no_deco\" id=\"prev\" href='/".$this->cal_uri."/".$this->service."/".$this->prevday."'>&lt;&lt;&nbsp;</a>";
						echo date("F", mktime(0,0,0,$this->month,$this->day,$this->year)); echo " ".$this->day; 
						echo "<a class=\"no_deco\" id=\"next\" href='/".$this->cal_uri."/".$this->service."/".$this->nextday."'>&nbsp;&gt;&gt;</a>";
					}else{
						echo date("F", mktime(0,0,0,$this->month,$this->day,$this->year)); echo " ".$this->day; 
						echo "<a class=\"no_deco\" href='/".$this->cal_uri."/".$this->service."/".$this->nextday."'>&nbsp;&gt;&gt;</a>";
					}
				?>
			</h1>
			<table>
				<thead>
					<tr><th>
						<?php 
							echo date("l", mktime(0,0,0,$this->month,$this->day,$this->year)); 
						?>
					</th></tr>
				</thead>
			<tbody>
			<?php
			foreach ($this->free_timeslots as $free_timeslot) {
					echo "<tr><td><a href='/".$this->cal_uri."/".$this->service."/".$this->year."/".$this->month."/".$this->day."/".$free_timeslot['hour']."'>".$free_timeslot["from"]." - ".$free_timeslot["to"]."</a></td></tr>";
			}
			?>
			</tbody>
		</table>
	</form>
</div>
</div>

<script src="/js/components/Calendar.js" type="text/javascript"></script>