<?php foreach ($this->events as $event) {?>
<event>
	<id><?php echo $event["event_id"]; ?></id>
	<client>
		<client_id><?php echo $event["client_id"]; ?></client_id>
		<client_name><?php echo $event["client_name"]; ?></client_name>
		<client_email><?php echo $event["client_email"]; ?></client_email>
		<client_phone></client_phone>
	</client>
	<service>
		<service_uri><?php echo $event["service_uri"]; ?></service_uri>
		<service_name><?php echo $event["service_name"]; ?></service_name>
	</service>
	<description><?php echo $event["description"]; ?></description>
	<from><?php echo gmdate('r', strtotime($event["from"])); ?></from>
	<to><?php echo gmdate('r', strtotime($event["to"])); ?></to>
</event>
<?php } ?>