<?php echo '<?xml version="1.0" encoding="UTF-8"?>' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Day overview</title>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<meta http-equiv="content-style-type" content="text/css"/>
<link href="/css/components/my_plan_style.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="container">

	<div id="message_bar_container">
		<div id="message_bar">
			Working offline!
		</div>
	</div>

	<div id="navigation_container">
		<div id="navigation">
			<a id="navigation_home" href="/" title="Back to main page">Regix</a>
			<a id="navigation_prev" title="Previous date"></a>
			<a id="navigation_now" title="Current time"></a>
			<a id="navigation_next" title="Next date"></a>
		</div>
	</div>
	
	<div id="content_container">
	
		<!-- Timeline -->
		
		<div id="timeline_wrapper">
			<div id="timeline">
				<div id="current_time_line"></div>
				<div id="timeline_slot_tpl" class="timeline_slot">
					<div class="timeline_slot_time_wrapper">
						<span class="time_slot_from"></span> &mdash; <span class="time_slot_to"></span>
					</div>
				</div>
			</div>
		</div>
		
		<!-- Event details -->
		
		<div id="event_bar_wrapper">
			<div id="event_bar">
				<div id="event_tpl" class="event">
					<div class="event_data_wrapper">
						<div class="event_time"></div>
						<div class="event_service_data_container">
							Service: <span class="event_service_name"></span> (<span class="event_service_uri"></span>)
						</div>
						<div class="event_client_name"></div>
						<div class="event_client_detail_container">
							<span class="event_client_email"></span>
						</div>
						<div class="event_client_detail_container">
							<span class="event_client_phone"></span>
						</div>
						<div class="event_description"></div>
					</div>
				</div>
				<div id="event_placeholder_tpl" class="event_placeholder">
					<div>
						No events booked
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>

<script type="text/javascript" src="/js/libs/jquery-2.1.0.min.js"></script>
<script type="text/javascript" src="/js/components/Calendar.js"></script>

<script type="text/javascript">
// Settings and startup
var from = new Date("<?php echo $this->from; ?>");
var to = new Date("<?php echo $this->to; ?>");
var prev = new Date("<?php echo $this->prev; ?>");
var next = new Date("<?php echo $this->next; ?>");
var url = "/myplan/ajax/" + from.getFullYear() + "/" + (from.getMonth() + 1) + "/" + from.getDate();

sui = new SlottedUI(from, to, 10, 2000, prev, next);

sui.start();
sui.showSlot(sui.timeToSlot(sui.getSystemTime()));
</script>
</body>
</html>