<div id="user_bar"><?php echo $this->user_name; ?></div>
<div id="user_profile_container">
		<table id="user_profile">
			<tr>
				<td>Name:</td><td><?php echo $this->user_name; ?></td>
			</tr>
			<tr>
				<td>Login:</td><td><?php echo $this->user_login; ?></td>
			</tr>
			<tr>
				<td>E-mail:</td><td><?php echo $this->user_email; ?></td>
			</tr>
			<tr>
				<td>Groups:</td>
				<td>
					<?php
					foreach ($this->user_group as $group_name) {
						echo($group_name); //show elements of array in a user-friendly way
						echo '<br />';
					}
					?>
				</td>
			</tr>
		</table>
</div>