<div class="regix-form-container">
	<form action="" method="post" class="regix-form">
		<h1>Add category</h1>
		<div class="form-label-container"><label for="name">Category name</label></div>
		<div><input id="name" type="text" name="name" class="regix-form-input" value="New Category"/></div>	
		<div><button name="submit" type="submit" class="secondary-button-single last">Create category</button></div>		
	</form>
</div>