<div class="regix-form-container">
	<form action="#" class="regix-form">
	<h1>Permissions catergories</h1>
<div class="table-content">
		<table class="hover-row">
		<thead>
			<tr><th>Name</th><th>Remove</th></tr>
		</thead>
		<tbody>
	<?php	
		if ($this->categories){
			foreach ($this->categories as $category) {
	?>
				<tr onclick="location.href='/<?php echo ($this->controller_uri_name . "/edit_category/" . $category["id"]); ?>'">
					<td>
						<?php echo $category["name"]; ?>
					</td>
					<td>
						<a href="/<?php echo ($this->controller_uri_name . '/delete_category/' . $category['id']); ?>">remove</a>
					</td>
				</tr>
	<?php
			} 
		}
	?>
		</tbody>
	</table>
</div>
	</form>
</div>


<div class="regix-form-container">
	<div class="button-holder">
	<form action="/<?php echo $this->controller_uri_name; ?>/add_category" method="post" class="regix-form">
		<div><button type="submit" class="secondary-button-single last"> Add category</button></div>		
	</form>
	</div>
</div>