<div id="permission_manager_add_container" class="table_container">
	<h3 class="title_block">Add permission</h3>
	<div>
		<form action="" method="post">
		
			<table>
				<tbody>
					<tr>
						<td>
							<label for="name">Permission name</label>
						</td>
						<td>
							<input id="name" name="name" type="text" value="new_permission"/>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="category_name">Category</label>
						</td>
						<td>
							<select id="category_name" name="category_name">
								<?php foreach ($this->categories as $category) { ?>
								<option><?php echo $category["name"]; ?></option>
								<?php } ?>
							</select>
						</td>
					</tr>
					
					<tr>
						<td>
							<label for="description">Description</label>
						</td>
						<td>
							<input id="description" name="description" type="text" value="Description."/>
						</td>
					</tr>
				</tbody>
			</table>
			
			<div class="single_button_container">
				<button name="submit" type="submit">Create permission</button>
			</div>
		</form>
	</div>
</div>