<div class="regix-form-container">
	<form action="#" class="regix-form">
	<h1>Permissions</h1>
<div class="table-content">
		<table class="hover-row">
		<thead>
			<tr><th>Category</th><th>Name</th><th>Description</th><th>Remove</th></tr>
		</thead>
		<tbody>
	<?php	
		if ($this->permissions){
			foreach ($this->permissions as $permission) {
	?>
				<tr onclick="location.href='/<?php echo ($this->controller_uri_name . "/edit/" . urlencode($permission["name"])); ?>'">
					<td>
						<?php echo $permission["category_name"]; ?>
					</td>
					<td>
						<?php echo $permission["name"]; ?>
					</td>
					<td>
						<?php echo $permission["description"]; ?>
					</td>
					<td class="last">
						<a href="<?php echo ($this->controller_uri_name . '/delete/' . urlencode($permission['name'])); ?>">remove</a>
					</td>
				</tr>
	<?php
			} 
		}
	?>
		</tbody>
	</table>

</div>
		</form>
	</div>

<div class="regix-form-container">
	<div class="button-holder">
	<form action="/<?php echo $this->controller_uri_name; ?>/add" method="post">
		<div><button type="submit" class="secondary-button-single" >Add permission</button></div></form>
	<form action="/<?php echo $this->controller_uri_name; ?>/categories" method="post">
		<div><button type="submit" class="default-button-single" >Categories</button></div></form>
	</div>
</div>