<div class="regix-form-container">
	<form action="#" method="post" class="regix-form">
		<h1>Edit permission</h1>
		<div class="form-label-container"><label for="name">Name</label></div>	
		<div><input id="name" type="text" name="name" class="regix-form-input" value="<?php echo $this->permission_data['name']; ?>"/></div>
		<div class="form-label-container"><label for="category_id">Category</label></div>
		<div><select id="category_id" name="category_id">
							<?php foreach ($this->categories as $category) { ?>
							<option value="<?php echo $category["id"]; ?>"<?php if ($category["id"] == $this->permission_data["permission_category_id"]) { echo ' selected="selected"'; } ?>><?php echo $category["name"]; ?></option>
							<?php } ?>
						</select></div>
		<div class="form-label-container"><label for="description">Description</label></div>	
		<div><input id="description" type="text" name="description" class="regix-form-input" value="<?php echo $this->permission_data['description']; ?>"/></div>
		<div><button name="submit" type="submit" class="secondary-button-single" >Save</button></div>		
	</form>
	<form action="/<?php echo ($this->controller_uri_name . "/delete/" . urlencode($this->permission_data['name'])); ?>">
		<div><button name="submit" type="submit" class="warning-button-single last" >Delete permission</button></div>
	</form>
</div>