<div id="permission_manager_category_add_container" class="table_container">
	<h1 class="title_block">Add category</h1>
	
	<form action="" method="POST">
		<table>
			<tbody>
				<tr>
					<td>
						Name
					</td>
					<td>
						<input id="name" name="name" type="text" value="New Category"/>
					</td>
				</tr>
			</tbody>
		</table>
		<div class="single_button_container">
			<button id="submit" name="submit" type="submit">Save</button>
		</div>
	</form>
</div>