<div class="regix-form-container">
	<form action="#" method="post" class="regix-form">
		<h1>Add permission</h1>
		<div class="form-label-container"><label for="name">Permission name</label></div>	
		<div><input id="name" type="text" name="name" class="regix-form-input" value="new_permission"/></div>
		<div class="form-label-container"><label for="category_name">Category</label></div>
		<div><select id="category_name" name="category_name">
								<?php foreach ($this->categories as $category) { ?>
								<option><?php echo $category["name"]; ?></option>
								<?php } ?>
							</select></div>
		<div class="form-label-container"><label for="description">Description</label></div>	
		<div><input id="description" type="text" name="description" class="regix-form-input" value="Description."/></div>
		<div><button type="submit" class="secondary-button-single" >Create permission</button></div>		
	</form>
</div>
