<div id="table-content">
	<table cellspacing="0">
		<thead>
			<tr><th>ID</th><th>Name</th><th>Login</th><th>Email</th><th>Remove</th></tr>
		</thead>
		<tbody>
	<?php
		if ($this->users){
			foreach ($this->users as $user) {
	?>
				<tr onclick="location.href='/<?php echo $this->editor_uri; ?>/edit/<?php echo $user['id']; ?>'">
					<td>
						<?php echo $user['id']; ?>
					</td>
					<td>
						<?php echo $user['name']; ?>
					</td>
					<td>
						<?php echo $user['login']; ?>
					</td>
					<td>
						<?php echo $user['email']; ?>
					</td>
					<td>
						<?php if ($user['id'] != 1) { ?>
						<a href="/<?php echo $this->editor_uri; ?>/delete/<?php echo $user['id']; ?>">remove</a>
						<?php }; ?>
					</td>
				</tr>
	<?php
			} 
		}
	?>
		</tbody>
	</table>

<div class="regix-form-container">
	<div class="button-holder">
	<form action="/<?php echo $this->editor_uri; ?>/add" method="post" class="regix-form">
		<div><button type="submit" class="secondary-button-single" > Add user</button></div>		
	</form>
	</div>
</div>