<div id="user_manager_list_container" class="table_container">
	<div class="title_block">Users</div>
	<table class="table_borders highlight_row cursor_pointer">
		<thead>
			<tr><th>ID</th><th>Name</th><th>Login</th><th>Email</th><th>Remove</th></tr>
		</thead>
		<tbody>
	<?php
		if ($this->users){
			foreach ($this->users as $user) {
	?>
				<tr onclick="location.href='/<?php echo $this->editor_uri; ?>/edit/<?php echo $user['id']; ?>'">
					<td>
						<?php echo $user['id']; ?>
					</td>
					<td>
						<?php echo $user['name']; ?>
					</td>
					<td>
						<?php echo $user['login']; ?>
					</td>
					<td>
						<?php echo $user['email']; ?>
					</td>
					<td>
						<?php if ($user['id'] != 1) { ?>
						<a href="/<?php echo $this->editor_uri; ?>/delete/<?php echo $user['id']; ?>">remove</a>
						<?php }; ?>
					</td>
				</tr>
	<?php
			} 
		}
	?>
		</tbody>
	</table>
	<div id="single_button_container"><button onclick="location.href='/<?php echo $this->editor_uri; ?>/add'">Add user</button></div>
</div>