<div class="regix-form-container">
	<form action="/<?php echo $this->editor_uri; ?>/save/<?php echo $this->edit_user_id; ?>" method="post" class="regix-form">
		<h1><?php echo $this->edit_user['name']; ?></h1>

		<div>
			<div class="form-label-container"><label for="name">Name</label></div>
			<input id="name" type="text" name="name" class="regix-form-input" value="<?php echo $this->edit_user['name']; ?>" />
		</div>

		<div>
			<div class="form-label-container"><label for="login">Login</label></div>
			<input id="login" type="text" name="login" class="regix-form-input" value="<?php echo $this->edit_user['login']; ?>" />
		</div>

		<div>		
			<div class="form-label-container"><label for="password">Password</label></div>
			<input id="password" type="password" name="password" class="regix-form-input" value=""/>
		</div>

		<div>
			<div class="form-label-container"><label for="email">Email</label></div>
			<input id="email" type="text" name="email" class="regix-form-input" value="<?php echo $this->edit_user['email']; ?>" />
		</div>   

		<h1>Groups</h1>
		<div class="form-label-container-center">
			<?php
				foreach ($this->edit_user["group_data"] as $group) { ?>
			<label for="group_<?php echo(base64_encode($group["group_name"]));?>">
					<?php echo($group["group_name"]);?>
			</label>
					<input id="group_<?php echo(base64_encode($group["group_name"]));?>" name="user_groups[]" value="<?php echo($group["group_name"]); ?>" type="checkbox"<?php if ($group["user_registered"]) echo(' checked="checked"');?> />
					<?php 
					echo '<br />';
				}
			?>

		</div>
                
			<div><button name="submit" type="submit" class="secondary-button-single">Save</button></div>
	</form>
<form action="/" class="regix-form">
	<div><button name="cancel" type="submit" class="default-button-single">Cancel</button></div>
</form>
</div>