<div class="regix-form-container">
	<form action="" method="post" class="regix-form">
		<h1>Registration</h1>
		<div class="form-label-container"><label for="name">Your name</label></div>
		
		<div><input id="name" type="text" name="name" class="regix-form-input"/></div>
		
		<div class="form-label-container"><label for="username">Username</label></div>
		
		<div><input id="username" type="text" name="username" class="regix-form-input"/></div>
		
		<div class="form-label-container"><label for="password">Password</label></div>
		
		<div><input id="password" type="password" name="password" class="regix-form-input"/></div>
		
		<div class="form-label-container"><label for="password2">Retype password</label></div>
		
		<div><input id="password2" type="password" name="password2" class="regix-form-input"/></div>
		
		<div class="form-label-container"><label for="email">Email</label></div>
		
		<div><input id="email" type="text" name="email" class="regix-form-input"/></div>
		
		<div><button type="submit" class="secondary-button-single" >Register</button></div>		
	</form>
</div>
