<div id="registration_form_container">
	<form action="" method="post">
		<table id="login_table">
			<tr>
				<td>Username:</td>
				<td><input name="username" type="text"></td>
			</tr>
			<tr>
				<td>Password:</td>
				<td><input name="password" type="password"></td>
			</tr>
			<tr>
				<td>Retype password:</td>
				<td><input name="repassword" type="password"></td>
			</tr>
			<tr>
				<td>E-mail:</td>
				<td><input name="email" type="email"></td>
			</tr>
			<tr>
				<td colspan="2"><input name="reg_user" type="submit" value="Register"></td>
			</tr>
		</table>
	</form>
</div>