<div class="regix-form-container">
	<h1>Events</h1>
	<div class="table-content">
		<table class="hover-row">
			<thead>
				<tr><th>ID</th><th>From</th><th>To</th><th>Worker</th><th>Description</th><th>Client</th><th>Service</th><th>Remove</th></tr>
			</thead>
			<tbody>
		<?php
			if ($this->events){
				foreach ($this->events as $event) {
		?>
					<tr onclick="location.href='/<?php echo $this->editor_uri; ?>/edit/<?php echo $event['id']; ?>'">
						<td>
							<div>
							<?php echo $event['id']; ?>
							</div>
						</td>
						<td>
							<div>
							<?php echo $event['from']; ?>
							</div>
						</td>
						<td>
							<div>
							<?php echo $event['to']; ?>
							</div>
						</td>
						<td>
							<div>
							<?php echo $event['worker']; ?>
							</div>
						</td>
						<td>
							<div>
							<?php echo $event['description']; ?>
							</div>
						</td>
						<td>
							<div>
							<?php echo $event['client']; ?>
							</div>
						</td>
						<td>
							<div>
							<?php echo $event['service']; ?>
							</div>
						</td>
						<td>
							<div>
							<?php if ($event['id'] != 1) { ?>
							<a href="/<?php echo $this->editor_uri; ?>/delete/<?php echo $event['id']; ?>">remove</a>
							<?php }; ?>
							</div>
						</td>
					</tr>
		<?php
				} 
			}
		?>
			</tbody>
		</table>
	</div>
	<div id="single_button_container"><button name="submit" type="submit" onclick="location.href='/calendar'" class="secondary-button-single first">Add event</button></div>
</div>