<div id="event_manager_editor_container" class="regix-form-container">
	<h1>Edit Event</h1>
	<form
		action="/<?php echo $this->editor_uri; ?>/save/<?php echo $this->edit_event_id; ?>"
		method="post"
		class="regix-form">
		<div>
			<div class="form-label-container"><label for="from">Time from</label></div>
			<input id="from" type="text" name="from" class="regix-form-input" value="<?php echo $this->edit_event['from']; ?>" />
		</div>
	
		<div>
			<div class="form-label-container"><label for="to">Time to</label></div>
			<input id="to" type="text" name="to" class="regix-form-input" value="<?php echo $this->edit_event['to']; ?>" />
		</div>		
		
		<div>
			<div class="form-label-container"><label for="worker">Worker</label></div>
			<input id="worker" type="text" name="from" class="regix-form-input" value="<?php echo $this->edit_event['worker']; ?>" />
			</div>
		
		<div>
			<div class="form-label-container"><label for="description">Description</label></div>
			<input id="description" type="text" name="description" class="regix-form-input" value="<?php echo $this->edit_event['description']; ?>" />
		</div>
		
		<div>
			<div class="form-label-container"><label for="client">Client</label></div>
			<input id="client" type="text" name="client" class="regix-form-input" value="<?php echo $this->edit_event['client']; ?>" />
		</div>
		
		<div>
			<div class="form-label-container"><label for="service">Service</label></div>
			<input id="service" type="text" name="service" class="regix-form-input" value="<?php echo $this->edit_event['service']; ?>" />
		</div>
	
		<div>
			<button name="submit" type="submit" class="secondary-button">Save</button> <button name="cancel" type="submit" class="default-button last">Cancel</button>
		</div>
	</form>
</div>