<div class="regix-form-container">
	<form action="/login" method="post" class="regix-form">
		<h1>Sign in</h1>
		<div>
			<div class="form-label-container"><label for="login">Login</label></div>
			<input id="login" type="text" name="login" class="regix-form-input"/>
		</div>
		<div>
			<div class="form-label-container"><label for="password" class="form-label">Password</label></div>
			<input id="password" type="password" name="password" class="regix-form-input"/>
		</div>
		<div>
			<button name="submit" type="submit" class="default-button-single">Login</button>
		</div>
		<?php if($this->redirect_to) { ?>
		<input id="redirect_to" name="redirect_to" type="hidden" value="<?php echo base64_encode($this->redirect_to); ?>" />
		<?php } ?>
	</form>
	<form action="/reg">
		<div>
			<button name="submit" type="submit" class="secondary-button-single last">Register</button>
		</div>
	</form>
</div>