<div class="regix-form-container">
	<form action="/login" method="post" class="regix-form">
		<h1>Sign in</h1>
		<div>
			<label for="login">Login</label>
			<input id="login" type="text" name="login" class="regix-form-input" placeholder="Login" />
		</div>
		<div>
			<label for="password">Password</label>
			<input id="password" type="password" name="password" class="regix-form-input" placeholder="Password" />
		</div>
		<div>
			<button type="submit" class="default-button-single">Login</button>
		</div>
	</form>
	<form action="/reg">
		<div>
			<button type="submit" class="secondary-button-single" >Register</button>
		</div>
	</form>
</div>