<div class="regix-form-container">
	<form action="#" class="regix-form">
	<h1>Groups</h1>
<div class="table-content">
		<table class="hover-row">
		<thead>
			<tr><th>Name</th></tr>
		</thead>
		<tbody>
	<?php	
		if ($this->groups){
			foreach ($this->groups as $group) {
	?>
				<tr onclick="location.href='/<?php echo ($this->controller_uri_name . "/edit/" . urlencode($group['name'])); ?>'">
					<td>
						<?php echo $group['name']; ?>
					</td>
				</tr>
	<?php
			} 
		}
	?>
		</tbody>
	</table>
</div>
	</form>		

	<div class="button-holder">
	<form action="/<?php echo $this->controller_uri_name; ?>/add" class="regix-form">
		<div><button type="submit" class="secondary-button-single first" >Add group</button></div>		
	</form>
	</div>
	
	<div class="button-holder">
	<form action="/<?php echo $this->controller_uri_name; ?>/add" class="regix-form">
		<div><button type="submit" class="default-button-single last" >Categories</button></div>		
	</form>
	</div>
</div>