<div class="regix-form-container">
	<form action="#" class="regix-form">
		<h1>
			<?php echo $this->group_name; ?></h1>
		<div class="table-content">
			<table>
				<thead>
					<tr>
						<th colspan="2">Users not in group</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->users_not_in_group as $user) { ?>
					<tr>
						<td>
							<?php echo($user["name"]); ?>
						</td>
						<td>
							<a href="/<?php echo($this->controller_uri_name . "/add_user_by_id/" . urlencode($this->group_name) . '/' . $user["id"]); ?>">add to group</a>
						</td>
					</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>
	</form>
</div>
