<div class="regix-form-container">
	<form action="#" class="regix-form">
		<h1>
			<?php echo $this->group_name;?></h1>
		<div class="table-content">
				<table class="hover-row">
				<thead>
					<tr>
						<th colspan="2">Permissions not granted to group</th>
					</tr>
				</thead>
						<tbody>
<?php
	foreach ($this->permissions_not_granted as $permission) {
?>
			<tr>
				<td>
					<?php echo($permission["name"]); ?>
				</td>
				<td>
					<a href="/<?php echo($this->controller_uri_name . "/add_permission/" . urlencode($this->group_name) . '/' . urlencode($permission["name"])); ?>">grant</a>
				</td>
			</tr>
<?php
	}
?>
		</tbody>
			</table>
		</div>
	</form>
</div>