<div id="group_manager_permission_category_list_container" class="table_container">
	<div class="title_block">Permission Categories</div>
	<table class="table_borders highlight_row cursor_pointer">
		<thead>
			<tr><th>Name</th></tr>
		</thead>
		<tbody>
	<?php	
		if ($this->groups){
			foreach ($this->groups as $group) {
	?>
				<tr onclick="location.href='/<?php echo ($this->controller_uri_name . "/edit/" . urlencode($group['name'])); ?>'">
					<td>
						<?php echo $group['name']; ?>
					</td>
				</tr>
	<?php
			} 
		}
	?>
		</tbody>
	</table>
	<div class="single_button_container">
		<button onclick="location.href='/<?php echo $this->controller_uri_name; ?>/add'">Add group</button>
	</div>
</div>