<div class="regix-form-container">
	<form action="add" method="post" class="regix-form">
		<h1>Add group</h1>
		<div class="form-label-container"><label for="name">Group name</label></div>
	
		<div><input id="name" type="text" name="name" class="regix-form-input" value="New Group"/></div>
		
		<div><button name="submit" type="submit" class="secondary-button-single last" >Create group</button></div>
	</form>
</div>