<div id="group_manager_add_user_container" class="table_container">
	<div class="title_block"><?php echo $this->group_name; ?></div>
	
	<h3 class="editor_section_header">Permissions not granted to group</h3>
	
	<table>
		<tbody>
<?php
	foreach ($this->permissions_not_granted as $permission) {
?>
			<tr>
				<td>
					<?php echo($permission["name"]); ?>
				</td>
				<td>
					<a href="/<?php echo($this->controller_uri_name . "/add_permission/" . urlencode($this->group_name) . '/' . urlencode($permission["name"])); ?>">grant</a>
				</td>
			</tr>
<?php
	}
?>
		</tbody>
	</table>
</div>