<div id="group_manager_list_container" class="table_container">
	<div class="title_block">Groups</div>
	<table class="table_borders highlight_row cursor_pointer">
		<thead>
			<tr><th>Name</th></tr>
		</thead>
		<tbody>
	<?php	
		if ($this->groups){
			foreach ($this->groups as $group) {
	?>
				<tr onclick="location.href='/<?php echo $this->editor_uri; ?>/edit/<?php echo urlencode($group['name']) ?>'">
					<td>
						<?php echo $group['name']; ?>
					</td>
				</tr>
	<?php
			} 
		}
	?>
		</tbody>
	</table>
	<div class="single_button_container">
		<button onclick="location.href='/<?php echo $this->editor_uri; ?>/add'">Add group</button>
	</div>
</div>